### ISSUE TITLE
Enhancement README.md project description and goals

### ISSUE THREAD

**Issue by helderburato** [helderburato/maximus#27]
## Description

Determine the problems this package is proposed to solve, the goals and write a better `README.md` to make more readable and understandable for users who want to use this package.

## Context

The idea has started based on these packages: [Ramda](https://github.com/ramda/ramda) and [Lodash](https://github.com/lodash/lodash), but I think these projects solve very well the problems that are proposed to solve.

Maybe we can think of a more lightweight and focused on functional programming toolkit, what do you think?

**Comment by karranb** [comment]
I think this project could focus on being a fp tool-belt. These are some cool functions that I think we should implement:

- compose
- pipe
- curry
- memoize
- lenses
- reduce (objects and arrays)
- map (objects and arrays)

maybe filter (objects and arrays)

**Comment by helderburato** [comment]
I like this idea @karranb and IMO we can add methods to help to deal with arrays/objects.

What do you think @Mendrone, @danilowoz, @caiangums? 
It will be awesome to have some inputs about it. :D

**Comment by caiangums** [comment]
I think it'll be good having something like the basics for `Arrays`, as implemented by JS and extended to Objects. In functional languages, as everything is Data and Lists of Data, the basics should be dealing with this kind of thing:
- List: forEach, map, reduce, and filter
- Data: avoid mutations

Another (parallel?) step could be adding things like `compose` and `memoization`.

As a final thought, maybe consider using a library for testing like Jest and creating examples of usage of each function and examples of how the library deal with data and good practices.

**Comment by karranb** [comment]
```
Data: avoid mutations
```
it would be really nice to have a `sort` that doesn't mutate, 😂

**Comment by helderburato** [comment]
I was wondering about setting `common` utils to FP to import maybe with `import { curry } from 'maximus/common'` and break the other helpers like `arrays`, `objects` to improve the tree-shaking when importing this package.

**Comment by helderburato** [comment]
I think we have a consense about the goal of the project, what do you think about it?
@karranb @caiangums
